# Values file for Podinfo

image:
  repository: "###ZARF_CONST_IMAGE_REPO###"
  tag: "###ZARF_CONST_IMAGE_VERSION###"

podLabels:
  protect: keycloak
    
tls:
  certPath: "###ZARF_VAR_CERT_FILE###"

domain: "###ZARF_VAR_DOMAIN###"
istio:
  enabled: true
  podinfo:
    gateways:
      - istio-system/tenant
    hosts:
      - "###ZARF_VAR_SUBDOMAIN###.###ZARF_VAR_DOMAIN###"
